### ISSUE TITLE
[TASK] - Webuniversum: error stijl pushen

### ISSUE THREAD

**Issue by coemans** [milieuinfo/webcomponent-vl-ui-upload#55]
**Functionele beschrijving**
Error stijl pushen naar Webuniversum.

``` css
.vl-upload--error {
  .vl-upload__element {
    border-color: $upload-file-error-color;
    background-color: #fae6e6;
    .vl-upload__element__label > * {
      color: $upload-file-error-color;
    }
  }
}
```
